//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaProject0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Services
    {
        public int ServicesID { get; set; }
        public string Decription { get; set; }
        public string Title { get; set; }
        public string IconUrl { get; set; }
        public string Decription2 { get; set; }
    }
}
